apiVersion: apps/v1
kind: Deployment
metadata:
  name: { { include "productivity-tracker.fullname" . } }
  labels: { { - include "productivity-tracker.labels" . | nindent 4 } }
spec:
  replicas: { { .Values.replicaCount } }
  selector:
    matchLabels:
      { { - include "productivity-tracker.selectorLabels" . | nindent 6 } }
  template:
    metadata:
      labels:
        { { - include "productivity-tracker.selectorLabels" . | nindent 8 } }
    spec:
      containers:
        - name: { { .Chart.Name } }
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: { { .Values.image.pullPolicy } }
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          env:
            - name: DATABASE_URL
              value: { { .Values.env.DATABASE_URL | quote } }
            - name: AUTH_SECRET
              value: { { .Values.env.AUTH_SECRET | quote } }
          resources: { { - toYaml .Values.resources | nindent 12 } }
